import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*Header */}
        <div className="bg-purple-800 text-white p-4">
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/contact">Contact</Link>
              </li>
            </ul>
          </nav>
        </div>

        {/*Main */}
        <div className="flex flex-1">
          {/*Sidebar*/}
          <aside className="w-64 bg-purple-200 p-4 h-screen">
            <ul>
              <li className="text-black">
                <Link
                  href="/category/technology"
                  className="block py-2 hover:bg-purple-300"
                >
                  Technology
                </Link>
                <Link
                  href="/category/design"
                  className="block py-2 hover:bg-purple-300"
                >
                  Design
                </Link>
                <Link
                  href="/category/business"
                  className="block py-2 hover:bg-purple-300"
                >
                  Business
                </Link>
                <Link
                  href="/category/employment"
                  className="block py-2 hover:bg-purple-300"
                >
                  Employment
                </Link>
              </li>
            </ul>
          </aside>

          {/*Main Content */}
          <main className="flex-1 p-6 bg-white text-black">{children}</main>
        </div>
        {/*Footer*/}
        <footer className="bg-purple-800 text-white text-center p-4">
          <p>&copy; 2025 Layout concept </p>
        </footer>
      </body>
    </html>
  );
}
